---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: apache-servers
  ansible_connection: local
  ansible_verbose: true
  ansible_verbosity: 4
  ansible_apt_repo: ppa:ansible/ansible-2.1
  require_chef_for_busser: false
  requirements_path: requirements.yml
#  custom_pre_install_command: echo '** custom pre install***'
#  custom_post_install_command: echo '** custom post install***'
#  custom_pre_play_command: echo '** custom pre play***'
#  custom_post_play_command: echo '** custom post play***'
#  idempotency_test: true
#  extra_vars_file: 'group_vars/production.yml'
#  extra_vars:
#    test: testing
#  additional_ssh_private_keys:
#    - C:/repository/ansible_vagrant_repo/id_rsa

transport:
  max_ssh_sessions: 6

platforms:
  - name: centos-7.2
    driver_plugin: vagrant
    driver_config:
      box: bento/centos-7.2
    provisioner:
      require_pip: true
    verifier:
      env_vars:
        LOGIN_USER: vagrant
        LOGIN_PASSWORD: vagrant
  - name: puppetlabs/ubuntu-16.04-64-nocm
    driver_plugin: vagrant
    verifier:
      env_vars:
        LOGIN_USER: root
        LOGIN_PASSWORD: puppet
  - name: debian
    driver:
      box: debian/jessie64
      box_version: 8.7.0
  - name: debian-jessie-64
    driver:
      box: thoughtbot/debian-jessie-64
  - name: debian-8.7
    ansible_platform: debian
    ansible_version: 2.1
    sudo: true
    ansible_sudo: true
    update_package_repos: false
    driver_plugin: vagrant
    driver_config:
      box: bento/debian-8.7
  - name: ubuntu-16.04
    provisioner:
      ansible_connection: local
      ansible_host_key_checking: false
      ansible_version: 2.2.1.0
      idempotency_test: true
      require_ansible_repo: false
      require_chef_for_busser: false
      require_ruby_for_busser: false
      require_pip: true
      requirements_path: requirements.yml
#  - name: centos-7
#    driver_plugin: vagrant
#    driver_config:
#      box: centos-7
#      box_url: https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box
#      network:
#      - ['forwarded_port', {guest: 8080, host: 8080}]
#      - [ 'private_network', { ip: '192.168.33.11' } ]

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: ansible
    driver_config:
      network:
#      - ['private_network', { type: 'dhcp' }]
#      - [ 'private_network', { ip: '172.28.128.6' } ]
#      - [ 'private_network', { ip: '127.0.0.1' } ]
#      - ['public_network']
    verifier:
      default_pattern: true
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
      env_vars:
        TARGET_HOST: 127.0.0.1
        TARGET_PORT: 2222